services:
  nginx:
    image: nginx:mainline-alpine3.21
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html/frontend
    depends_on:
      - core-service
      - math-service
    networks:
      - app-network


  core-service:
    build:
      context: .
      dockerfile: ./core-service.DockerFile
    container_name: core-service
    networks:
      - app-network

  math-service:
    build:
      context: .
      dockerfile: ./math-service.DockerFile
    container_name: math-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
