services:
  nginx:
    image: nginx:mainline-alpine3.21
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - core-service
      - math-service

  core-service:
    image: alpine
    command: /bin/core-service
    volumes:
      - ./bin/core-service:/bin/core-service
    expose:
      - "80"


  math-service:
    image: alpine
    command: /bin/math-service
    volumes:
      - ./bin/math-service:/bin/math-service
    expose:
      - "80"
